2018-03-12 14:33:35 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第[TestResult name=function1 status=FAILURE method=test.function1()[pri:0, instance:ftnt.qa.autotest.ui.fortisiem.pageobject.test@4b4523f8] output={null}]次
2018-03-12 14:33:41 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第[TestResult name=function1 status=FAILURE method=test.function1()[pri:0, instance:ftnt.qa.autotest.ui.fortisiem.pageobject.test@4b4523f8] output={null}]次
2018-03-12 14:33:45 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第[TestResult name=function1 status=FAILURE method=test.function1()[pri:0, instance:ftnt.qa.autotest.ui.fortisiem.pageobject.test@4b4523f8] output={null}]次
2018-03-12 14:38:12 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 14:38:27 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第2次
2018-03-12 14:38:45 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第3次
2018-03-12 14:39:23 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function3>执行失败，重试第1次
2018-03-12 14:39:23 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function3>执行失败，重试第2次
2018-03-12 14:39:23 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function3>执行失败，重试第3次
2018-03-12 16:07:44 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 16:07:57 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第2次
2018-03-12 16:08:17 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第3次
2018-03-12 16:13:30 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 16:19:40 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 16:19:56 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function3>执行失败，重试第1次
2018-03-12 16:22:39 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 16:22:53 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function3>执行失败，重试第1次
2018-03-12 16:23:50 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 16:24:01 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function3>执行失败，重试第1次
2018-03-12 16:43:57 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 16:44:07 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function3>执行失败，重试第1次
2018-03-12 17:14:49 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 17:16:11 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 17:17:09 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 18:06:37 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function1>执行失败，重试第1次
2018-03-12 18:07:01 ftnt.qa.autotest.ui.framework.testng.listener.RetryToRunCase-INFO : 方法<function3>执行失败，重试第1次
